### ISSUE TITLE
Enemy chasing Player Units

### ISSUE THREAD

**Issue by 1man2kinds** [yosr481/chbd_edu_rts#12]
An 'Alert' Enemy will chase his 'Target' at the defined 'Chase Speed'.
If Enemy reaches the Player Unit then the Player Unit will be destroyed.

**Comment by yosr481** [comment]
More details required, how long the chase should be?
What happens when the player get away? Is the enemy get into seek mode?

**Comment by 1man2kinds** [comment]
Seek mode is a feature we can consider adding later.
