### ISSUE TITLE
Slow Movement

### ISSUE THREAD

**Issue by 1man2kinds** [yosr481/chbd_edu_rts#8]
Shift-Right click to move selected units to target at slow speed.

**Comment by yosr481** [comment]
This is working fine, but when I tried it in the game it is very unintuitive. We have to change the key combination for slow-mo.

**Comment by yosr481** [comment]
It was unintuitive when I used the Right-click + Left shift, now I changed it to Left-click + Left shift. It’s better.

**Comment by 1man2kinds** [comment]
`unintuitive` or rather that you are not `used` to the controls?
To be more precise, it is `unintuitive` to have the same exact control to select a unit and assign it i.e. Left-Click to select and Left-Click to set a target destination.
Wouldn't it be more `intuitive` to keep the Left-Click for Selecting and Deselecting (By clicking anywhere else in the game world) and use the Right-Click for assigning?
Alternatively you can use the Left-Click for assigning as well but the Mouse Cursor should have a different icon denoting that you are assigning and not selecting etc.
Another option is to have another button when a unit is selected to send the Cursor into assign mode. 
Either way this isn't critical for the time being so we can stay with your current controls and save this discussion for a later time.
